Better error messages

diff --git a/spellr/spellr b/spellr/spellr
--- a/spellr/spellr
+++ b/spellr/spellr
@@ -14,7 +14,9 @@ then
       export FILE_TO_CHECK="$(cat ${FILE})"
       podman run --rm --env FILE_TO_CHECK ${CONTANIER_IMAGE}
     else
-      echo "Run: podman pull ${CONTANIER_IMAGE}" 1>&2
+      echo "Missing container image: ${CONTANIER_IMAGE}" 1>&2
+      echo "Log in to quay.io and then run the following command:" 1>&2
+      echo "podman pull ${CONTANIER_IMAGE}" 1>&2
       exit 3
     fi
   else
diff --git a/vale/vale b/vale/vale
--- a/vale/vale
+++ b/vale/vale
@@ -12,7 +12,9 @@ then
     then
       podman run --rm -v $(pwd)/${FILE}:$(pwd)/${FILE}:Z ${CONTANIER_IMAGE} $(pwd)/${FILE}
     else
-      echo "Run: podman pull ${CONTANIER_IMAGE}" 1>&2
+      echo "Missing container image: ${CONTANIER_IMAGE}" 1>&2
+      echo "Log in to quay.io and then run the following command:" 1>&2
+      echo "podman pull ${CONTANIER_IMAGE}" 1>&2
       exit 3
     fi
   else
